language: go
go:
- 1.13.x
script:
- go test -v -race ./...

before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"

deploy:
  - #goreleaser
    provider: script
    script: curl -sL https://git.io/goreleaser | bash
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

env:
  global:
    - secure: WAMxanUvhYKXRNPWffAT89WDLKD57D7dSAAvBHaQDpGzVX9uQVt21lisbr+YeWq0E+Iokp0ef0ZrVIY12liFjKMcXTePS/fQZTSLzbY1krhLJc4b6d8ktwDHIwuThlkCT3oQJdlqYjMm1mp9XDeimo9KjDEouVZFlsZm+Xmyqx5wRTPBK6V7h7CUoLerIixnsjgr9ML0sa1/jRDZeQe/XCRYNXV5yNOk7VcUBhP9yx196oMIncxLaz5pIXyBb48wOspfQQnDCD4C87GCmUXatPlxFm0TW1kO9gqaAADJ3yCEoGkP6BXtmokz34DTu+Ygr7gkUeIr+WzMn83dsfbjYaKOxgcatRMF1vnA2Q9ocmSASd0mkvMm2cIaWMxn/e1Xv1r1RiQlAclaNS83ltQ8CfL6gQ1Hc2NJgMm4rgnmJIZHfalc5f6iFBPvQARERiLL+fcWXefbV9y5NweolFhsC91M221t8CCZqSIgKLhRVjNhUpKQWyGuSfG5GGz88LZMi3GEqG9IHsXfwxbPG3eHuCgNBIX5qUUoueBtg8V6ifRN9VJt3bOHyDR11RHP1N3HVNT6hpzDAzqiuXyCM1AG0TfWHw/IS9wHx13DJr4iLOclScJ2BFezjZFMzGZLqySJcC9e4b1Byk3bA7iWtgFPotcje91iTOsiClLGxRGLL4o=
